version: "3.8"

services:
  db:
    platform: linux/amd64
    container_name: nest_postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5431:5432"
    volumes:
      - ./nest_postgres_data:/var/lib/postgresql/data

  pgadmin:
    platform: linux/amd64
    container_name: nest_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./nest_pgadmin_data:/var/lib/pgadmin

volumes:
  nest_postgres_data:
  nest_pgadmin_data: